FROM ubuntu:18.04
RUN apt-get update 
RUN apt-get install apache2 -y
RUN rm -f /var/www/html/index.html
RUN echo "hoy me siento bien puta re piola" > /var/www/html/index.html
EXPOSE 80
CMD ["apachectl", "-D", "FOREGROUND"]